dist: trusty

branches:
  only:
    - master
node_js:
  - 5.5

language: node_js
env: NODE_ENV=test
cache:
  directories:
    - "$HOME/.nvm"
    - "$HOME/.npm"

before_install:
  - nvm install v5.5

install:
  - npm install

script:
  - npm test
